### ISSUE TITLE
Multisite Query Builder among WordPress tables

### ISSUE THREAD

**Issue by firomero** [Simettric/WPQueryBuilder#2]
How can I use this query builder inside a multi site plugin avoiding using the switch_to_blog function?
Best Regards!

**Comment by asiermarques** [comment]
You can´t :(

It makes use of the WP_Query object so you need to work in "a blog context". 
The only way to do this is using the switch_to_blog function. 

Note: If your multisite is big and you have hundreds of blogs, you probably want to have an intermediate table with a custom structure to make this sort of queries and return only an array of IDs to operate with them.
